module.exports = {
  theme: {
    fontFamily: {
      body: ["Lato", "sans-serif"],
      display: ["Titillium Web", "sans-serif"],
    },
    borderRadius: {
      large: "46px",
      circle: "50%",
      small: "9px",
      card: "11px",
      form: "7px",
    },
    extend: {
      colors: {
        "primary-blue": "#2F8BCB",
        "dark-blue": "#253670",
        "light-blue": "#95B8E1",
        "brown-accent": "#401F3E",
        "orange-accent": "#E88D17",
        "white-color": "#F4F7F9",
        "bluish-white": "#E8EFF6",
        "gray-color": "#84898D",
        "border-white": "#5DB1EB",
        "card-blue": "#3A95D5",
        "card-border": "#7BC1F2",
        "header-white": "#E8F5FF",
        "subheader-white": "#AAD9FA",
        "faded-blue": "#51A6E1",
        "contact-blue": "#CAE7FB",
        "form-white": "#FDFDFD",
        input: "#f4f4f4",
        "label-gray": "#A6A6A6",
        "contact-border": "#E0E0E0",
        "dark-blue": "#7699CB",
        purple: "#162557",
      },
      spacing: {
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
      },
      maxWidth: {
        card: "220px",
      },
    },
  },
  variants: {},
  plugins: [],
}
